### ISSUE TITLE
unusedCompileDependencies is reporting false positives / does not work

### ISSUE THREAD

**Issue by Sciss** [cb372/sbt-explicit-dependencies#22]
The following illustrates the problem:

```
$ sbt unusedCompileDependencies
[info] Set current project to Mellite (in build file:~/Documents/devel/Mellite/)
[info] Compiling 206 Scala sources to ~/Documents/devel/Mellite/target/scala-2.12/classes ...
[info] Done compiling.
[warn] Mellite >>> The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "de.sciss" %% "audiowidgets-app" % "1.14.0"
[warn]  - "de.sciss" %% "audiowidgets-swing" % "1.14.0"
[warn]  - "de.sciss" %% "desktop" % "0.10.0"
[warn]  - "de.sciss" %% "equal" % "0.1.3"
[warn]  - "de.sciss" %% "fingertree" % "1.5.4"
[warn]  - "de.sciss" %% "fscape" % "2.20.0"
[warn]  - "de.sciss" % "jump3r" % "1.0.5"
[warn]  - "de.sciss" %% "kollflitz" % "0.2.3"
[warn]  - "de.sciss" %% "lucre-bdb" % "3.11.0"
[warn]  - "de.sciss" %% "lucre-core" % "3.11.0"
[warn]  - "de.sciss" %% "lucre-expr" % "3.11.0"
[warn]  - "de.sciss" %% "lucreswing" % "1.14.0"
[warn]  - "de.sciss" %% "numbers" % "0.2.0"
[warn]  - "de.sciss" %% "patterns-lucre" % "0.7.0"
[warn]  - "de.sciss" %% "pdflitz" % "1.4.0"
[warn]  - "de.sciss" %% "raphael-icons" % "1.0.5"
[warn]  - "de.sciss" %% "scalacollider" % "1.28.0"
[warn]  - "de.sciss" %% "scalacolliderswing-core" % "1.41.0"
[warn]  - "de.sciss" %% "scalacolliderswing-interpreter" % "1.41.0"
[warn]  - "de.sciss" % "scalacolliderugens-spec" % "1.19.2"
[warn]  - "de.sciss" %% "scalafreesound" % "1.13.0"
[warn]  - "de.sciss" %% "scalainterpreterpane" % "1.10.0"
[warn]  - "de.sciss" %% "sonogramoverview" % "1.11.0"
[warn]  - "de.sciss" %% "soundprocesses-compiler" % "3.24.0"
[warn]  - "de.sciss" %% "soundprocesses-views" % "3.24.0"
[warn]  - "de.sciss" %% "span" % "1.4.2"
[warn]  - "de.sciss" % "submin" % "0.2.4"
[warn]  - "de.sciss" %% "swingplus" % "0.4.0"
[warn]  - "de.sciss" %% "topology" % "1.1.1"
[warn]  - "de.sciss" % "weblaf" % "2.1.4"
[warn]  - "de.sciss" %% "wolkenpumpe" % "2.29.0"
[warn]  - "jline" % "jline" % "2.14.6"
[success] Total time: 27 s, completed Jan 4, 2019 7:07:11 PM
```

Then I tentatively remove `submin` (which _I know_ is explicitly used) and rebuild:

```
$ vi build.sbt 
...
$ sbt update clean test
...
[info] Compiling 206 Scala sources to ~/Documents/devel/Mellite/target/scala-2.12/classes ...
[error] ~/Documents/devel/Mellite/src/main/scala/de/sciss/mellite/Prefs.scala:23:17: object submin is not a member of package de.sciss
[error] import de.sciss.submin.Submin
[error]                 ^
[error] ~/Documents/devel/Mellite/src/main/scala/de/sciss/mellite/Prefs.scala:71:29: not found: value Submin
[error]       def install(): Unit = Submin.install(false)
[error]                             ^
[error] ~/Documents/devel/Mellite/src/main/scala/de/sciss/mellite/Prefs.scala:78:29: not found: value Submin
[error]       def install(): Unit = Submin.install(true)
[error]                             ^
...
```

Of that initially reported list, I'm sure almost _all_ of those libraries are explicitly used in my project. So something goes bad... sbt version is 1.2.7.

**Comment by cb372** [comment]
Thanks for the report. I’ll take a look this weekend.

**Comment by cb372** [comment]
Now this is interesting. I cloned your repo, added the plugin (`0.2.6`) to plugins.sbt, and ran `unusedCompileDependencies`. I get quite different output to what you reported.

```
sbt:Mellite> clean
[success] Total time: 0 s, completed 05-Jan-2019 13:25:04
sbt:Mellite> unusedCompileDependencies
[info] Updating ...
[info] Done updating.
[info] Compiling 192 Scala sources to /Users/chris/code/Mellite/target/scala-2.12/classes ...
[warn] /Users/chris/code/Mellite/src/main/scala/de/sciss/mellite/gui/ActionBounceTimeline.scala:1149:42: parameter value tx in method defaultRealtime is never used
[warn]   protected def defaultRealtime(implicit tx: S#Tx): Boolean               = false
[warn]                                          ^
[warn] /Users/chris/code/Mellite/src/main/scala/de/sciss/mellite/gui/ActionBounceTimeline.scala:1150:42: parameter value tx in method defaultFile is never used
[warn]   protected def defaultFile    (implicit tx: S#Tx): File                  = file("")
[warn]                                          ^
[warn] /Users/chris/code/Mellite/src/main/scala/de/sciss/mellite/gui/ActionBounceTimeline.scala:1151:42: parameter value tx in method defaultChannels is never used
[warn]   protected def defaultChannels(implicit tx: S#Tx): Vec[Range.Inclusive]  = Vector(0 to 1)
[warn]                                          ^
[warn] /Users/chris/code/Mellite/src/main/scala/de/sciss/mellite/gui/impl/grapheme/GraphemeViewImpl.scala:355:27: parameter value tx in method objMoved is never used
[warn]                 (implicit tx: S#Tx): Unit = {
[warn]                           ^
[warn] /Users/chris/code/Mellite/src/main/scala/de/sciss/mellite/gui/impl/grapheme/GraphemeViewImpl.scala:398:46: parameter value tx in value $anonfun is never used
[warn]         val editOpt = cursor.step { implicit tx =>
[warn]                                              ^
[warn] 5 warnings found
[info] Done compiling.
[warn] Mellite >>> The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "de.sciss" %% "desktop" % "0.10.0"
[warn]  - "de.sciss" %% "fscape" % "2.20.0"
[warn]  - "de.sciss" %% "kollflitz" % "0.2.3"
[warn]  - "de.sciss" %% "scalacolliderswing-interpreter" % "1.41.0"
[warn]  - "de.sciss" % "scalacolliderugens-spec" % "1.19.2"
[warn]  - "de.sciss" % "weblaf" % "2.1.4"
[warn]  - "de.sciss" %% "wolkenpumpe" % "2.29.0"
[warn]  - "jline" % "jline" % "2.14.6"
[success] Total time: 29 s, completed 05-Jan-2019 13:25:35
```

Running again without cleaning:

```
sbt:Mellite> unusedCompileDependencies
[warn] Mellite >>> The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "de.sciss" %% "desktop" % "0.10.0"
[warn]  - "de.sciss" %% "fscape" % "2.20.0"
[warn]  - "de.sciss" %% "kollflitz" % "0.2.3"
[warn]  - "de.sciss" %% "scalacolliderswing-interpreter" % "1.41.0"
[warn]  - "de.sciss" % "scalacolliderugens-spec" % "1.19.2"
[warn]  - "de.sciss" % "weblaf" % "2.1.4"
[warn]  - "de.sciss" %% "wolkenpumpe" % "2.29.0"
[warn]  - "jline" % "jline" % "2.14.6"
[success] Total time: 1 s, completed 05-Jan-2019 13:28:20
```

I guess these dependencies really are unused?

So either this is an environment problem or there's some kind of nondeterminism. I'll keep trying to reproduce.

One question: do you use Coursier or the default Ivy-based resolution mechanism?

**Comment by cb372** [comment]
I tried with Coursier 1.0.3 (I had to mess around with the `com.sleepycat:je` dependency to get it to work), but I still can't reproduce the issue. I wonder what it could be?

By the way @laughedelic mentions a similar problem [here](https://gist.github.com/laughedelic/f16beb155ac2d258c1d06d7823d5ffc4), so you are not alone!

**Comment by cb372** [comment]
I've just published a version called `0.2.6-debug` which adds some debug logging to the `unusedCompileDependencies` task.

```
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.6-debug")
```

Please could you try with this version of the plugin and tell me what output you get. On my machine it looks like this:

```
Compile dependencies reported by Zinc:
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar
/Users/chris/.ivy2/cache/com.github.scopt/scopt_2.12/jars/scopt_2.12-3.7.1.jar
/Users/chris/.ivy2/cache/com.typesafe/config/bundles/config-1.3.3.jar
/Users/chris/.ivy2/cache/de.sciss/audiofile_2.12/jars/audiofile_2.12-1.5.1.jar
/Users/chris/.ivy2/cache/de.sciss/audiowidgets-app_2.12/jars/audiowidgets-app_2.12-1.14.0.jar
/Users/chris/.ivy2/cache/de.sciss/audiowidgets-core_2.12/jars/audiowidgets-core_2.12-1.14.0.jar
/Users/chris/.ivy2/cache/de.sciss/audiowidgets-swing_2.12/jars/audiowidgets-swing_2.12-1.14.0.jar
/Users/chris/.ivy2/cache/de.sciss/desktop-core_2.12/jars/desktop-core_2.12-0.10.0.jar
/Users/chris/.ivy2/cache/de.sciss/equal_2.12/jars/equal_2.12-0.1.3.jar
/Users/chris/.ivy2/cache/de.sciss/filecache-common_2.12/jars/filecache-common_2.12-0.5.0.jar
/Users/chris/.ivy2/cache/de.sciss/fileutil_2.12/jars/fileutil_2.12-1.1.3.jar
/Users/chris/.ivy2/cache/de.sciss/fingertree_2.12/jars/fingertree_2.12-1.5.3.jar
/Users/chris/.ivy2/cache/de.sciss/fscape-core_2.12/jars/fscape-core_2.12-2.20.0.jar
/Users/chris/.ivy2/cache/de.sciss/fscape-lucre_2.12/jars/fscape-lucre_2.12-2.20.0.jar
/Users/chris/.ivy2/cache/de.sciss/jump3r/jars/jump3r-1.0.5.jar
/Users/chris/.ivy2/cache/de.sciss/lucre-base_2.12/jars/lucre-base_2.12-3.11.0.jar
/Users/chris/.ivy2/cache/de.sciss/lucre-bdb_2.12/jars/lucre-bdb_2.12-3.11.0.jar
/Users/chris/.ivy2/cache/de.sciss/lucre-confluent_2.12/jars/lucre-confluent_2.12-3.11.0.jar
/Users/chris/.ivy2/cache/de.sciss/lucre-core_2.12/jars/lucre-core_2.12-3.11.0.jar
/Users/chris/.ivy2/cache/de.sciss/lucre-expr_2.12/jars/lucre-expr_2.12-3.11.0.jar
/Users/chris/.ivy2/cache/de.sciss/lucreswing_2.12/jars/lucreswing_2.12-1.14.0.jar
/Users/chris/.ivy2/cache/de.sciss/lucresynth_2.12/jars/lucresynth_2.12-3.24.0.jar
/Users/chris/.ivy2/cache/de.sciss/model_2.12/jars/model_2.12-0.3.4.jar
/Users/chris/.ivy2/cache/de.sciss/numbers_2.12/jars/numbers_2.12-0.2.0.jar
/Users/chris/.ivy2/cache/de.sciss/patterns-core_2.12/jars/patterns-core_2.12-0.7.0.jar
/Users/chris/.ivy2/cache/de.sciss/patterns-lucre_2.12/jars/patterns-lucre_2.12-0.7.0.jar
/Users/chris/.ivy2/cache/de.sciss/pdflitz_2.12/jars/pdflitz_2.12-1.4.0.jar
/Users/chris/.ivy2/cache/de.sciss/processor_2.12/jars/processor_2.12-0.4.2.jar
/Users/chris/.ivy2/cache/de.sciss/raphael-icons_2.12/jars/raphael-icons_2.12-1.0.5.jar
/Users/chris/.ivy2/cache/de.sciss/scalacollider_2.12/jars/scalacollider_2.12-1.28.0.jar
/Users/chris/.ivy2/cache/de.sciss/scalacolliderswing-core_2.12/jars/scalacolliderswing-core_2.12-1.41.0.jar
/Users/chris/.ivy2/cache/de.sciss/scalacolliderugens-api_2.12/jars/scalacolliderugens-api_2.12-1.19.2.jar
/Users/chris/.ivy2/cache/de.sciss/scalacolliderugens-core_2.12/jars/scalacolliderugens-core_2.12-1.19.2.jar
/Users/chris/.ivy2/cache/de.sciss/scalainterpreterpane_2.12/jars/scalainterpreterpane_2.12-1.10.0.jar
/Users/chris/.ivy2/cache/de.sciss/scalaosc_2.12/jars/scalaosc_2.12-1.2.0.jar
/Users/chris/.ivy2/cache/de.sciss/scissdsp_2.12/jars/scissdsp_2.12-1.3.1.jar
/Users/chris/.ivy2/cache/de.sciss/serial_2.12/jars/serial_2.12-1.1.1.jar
/Users/chris/.ivy2/cache/de.sciss/sonogramoverview_2.12/jars/sonogramoverview_2.12-1.11.0.jar
/Users/chris/.ivy2/cache/de.sciss/soundprocesses-compiler_2.12/jars/soundprocesses-compiler_2.12-3.24.0.jar
/Users/chris/.ivy2/cache/de.sciss/soundprocesses-core_2.12/jars/soundprocesses-core_2.12-3.24.0.jar
/Users/chris/.ivy2/cache/de.sciss/soundprocesses-views_2.12/jars/soundprocesses-views_2.12-3.24.0.jar
/Users/chris/.ivy2/cache/de.sciss/span_2.12/jars/span_2.12-1.4.2.jar
/Users/chris/.ivy2/cache/de.sciss/submin/jars/submin-0.2.4.jar
/Users/chris/.ivy2/cache/de.sciss/swingplus_2.12/jars/swingplus_2.12-0.4.0.jar
/Users/chris/.ivy2/cache/de.sciss/syntaxpane/jars/syntaxpane-1.2.0.jar
/Users/chris/.ivy2/cache/de.sciss/topology_2.12/jars/topology_2.12-1.1.1.jar
/Users/chris/.ivy2/cache/de.sciss/treetable-java/jars/treetable-java-1.5.0.jar
/Users/chris/.ivy2/cache/de.sciss/treetable-scala_2.12/jars/treetable-scala_2.12-1.5.0.jar
/Users/chris/.ivy2/cache/de.sciss/wolkenpumpe-basic_2.12/jars/wolkenpumpe-basic_2.12-2.29.0.jar
/Users/chris/.ivy2/cache/de.sciss/wolkenpumpe-core_2.12/jars/wolkenpumpe-core_2.12-2.29.0.jar
/Users/chris/.ivy2/cache/org.pegdown/pegdown/jars/pegdown-1.6.0.jar
/Users/chris/.ivy2/cache/org.scala-lang.modules/scala-swing_2.12/jars/scala-swing_2.12-2.1.0.jar
/Users/chris/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.8.jar
/Users/chris/.ivy2/cache/org.scala-stm/scala-stm_2.12/jars/scala-stm_2.12-0.9.jar

Declared library dependencies:
com.github.scopt:scopt:3.7.1
de.sciss:audiowidgets-app:1.14.0
de.sciss:audiowidgets-swing:1.14.0
de.sciss:desktop:0.10.0
de.sciss:equal:0.1.3
de.sciss:fileutil:1.1.3
de.sciss:fscape:2.20.0
de.sciss:jump3r:1.0.5
de.sciss:kollflitz:0.2.3
de.sciss:lucre-bdb:3.11.0
de.sciss:lucre-core:3.11.0
de.sciss:lucre-expr:3.11.0
de.sciss:lucreswing:1.14.0
de.sciss:model:0.3.4
de.sciss:numbers:0.2.0
de.sciss:patterns-lucre:0.7.0
de.sciss:pdflitz:1.4.0
de.sciss:raphael-icons:1.0.5
de.sciss:scalacollider:1.28.0
de.sciss:scalacolliderswing-core:1.41.0
de.sciss:scalacolliderswing-interpreter:1.41.0
de.sciss:scalacolliderugens-spec:1.19.2
de.sciss:scalainterpreterpane:1.10.0
de.sciss:sonogramoverview:1.11.0
de.sciss:soundprocesses-compiler:3.24.0
de.sciss:soundprocesses-views:3.24.0
de.sciss:span:1.4.2
de.sciss:submin:0.2.4
de.sciss:swingplus:0.4.0
de.sciss:topology:1.1.1
de.sciss:weblaf:2.1.4
de.sciss:wolkenpumpe:2.29.0
jline:jline:2.14.6
org.pegdown:pegdown:1.6.0
org.scala-lang:scala-library:2.12.8
```

**Comment by Sciss** [comment]
Thanks for investigating! I made a fresh clone and ran on master, so it should be identical to your build. This is the output:

```
Compile dependencies reported by Zinc:
/home/hhrutz/.ivy2/cache/com.github.scopt/scopt_2.12/jars/scopt_2.12-3.7.1.jar
/home/hhrutz/.ivy2/cache/com.typesafe/config/bundles/config-1.3.3.jar
/home/hhrutz/.ivy2/cache/de.sciss/fileutil_2.12/jars/fileutil_2.12-1.1.3.jar
/home/hhrutz/.ivy2/cache/de.sciss/model_2.12/jars/model_2.12-0.3.4.jar
/home/hhrutz/.ivy2/cache/de.sciss/serial_2.12/jars/serial_2.12-1.1.1.jar
/home/hhrutz/.ivy2/cache/org.pegdown/pegdown/jars/pegdown-1.6.0.jar
/home/hhrutz/.ivy2/cache/org.scala-lang.modules/scala-swing_2.12/jars/scala-swing_2.12-2.1.0.jar
/home/hhrutz/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.8.jar
/home/hhrutz/.ivy2/cache/org.scala-stm/scala-stm_2.12/jars/scala-stm_2.12-0.9.jar
/home/hhrutz/.ivy2/local/de.sciss/audiofile_2.12/1.5.1/jars/audiofile_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/audiowidgets-app_2.12/1.14.0/jars/audiowidgets-app_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/audiowidgets-core_2.12/1.14.0/jars/audiowidgets-core_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/audiowidgets-swing_2.12/1.14.0/jars/audiowidgets-swing_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/desktop-core_2.12/0.10.0/jars/desktop-core_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/equal_2.12/0.1.3/jars/equal_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/filecache-common_2.12/0.5.0/jars/filecache-common_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/fingertree_2.12/1.5.3/jars/fingertree_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/fscape-core_2.12/2.20.0/jars/fscape-core_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/fscape-lucre_2.12/2.20.0/jars/fscape-lucre_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/jump3r/1.0.5/jars/jump3r.jar
/home/hhrutz/.ivy2/local/de.sciss/lucre-base_2.12/3.11.0/jars/lucre-base_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/lucre-bdb_2.12/3.11.0/jars/lucre-bdb_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/lucre-confluent_2.12/3.11.0/jars/lucre-confluent_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/lucre-core_2.12/3.11.0/jars/lucre-core_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/lucre-expr_2.12/3.11.0/jars/lucre-expr_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/lucreswing_2.12/1.14.0/jars/lucreswing_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/lucresynth_2.12/3.24.0/jars/lucresynth_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/numbers_2.12/0.2.0/jars/numbers_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/patterns-core_2.12/0.7.0/jars/patterns-core_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/patterns-lucre_2.12/0.7.0/jars/patterns-lucre_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/pdflitz_2.12/1.4.0/jars/pdflitz_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/processor_2.12/0.4.2/jars/processor_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/raphael-icons_2.12/1.0.5/jars/raphael-icons_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/scalacollider_2.12/1.28.0/jars/scalacollider_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/scalacolliderswing-core_2.12/1.41.0/jars/scalacolliderswing-core_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/scalacolliderugens-api_2.12/1.19.2/jars/scalacolliderugens-api_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/scalacolliderugens-core_2.12/1.19.2/jars/scalacolliderugens-core_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/scalainterpreterpane_2.12/1.10.0/jars/scalainterpreterpane_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/scalaosc_2.12/1.2.0/jars/scalaosc_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/scissdsp_2.12/1.3.1/jars/scissdsp_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/sonogramoverview_2.12/1.11.0/jars/sonogramoverview_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/soundprocesses-compiler_2.12/3.24.0/jars/soundprocesses-compiler_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/soundprocesses-core_2.12/3.24.0/jars/soundprocesses-core_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/soundprocesses-views_2.12/3.24.0/jars/soundprocesses-views_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/span_2.12/1.4.2/jars/span_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/submin/0.2.4/jars/submin.jar
/home/hhrutz/.ivy2/local/de.sciss/swingplus_2.12/0.4.0/jars/swingplus_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/syntaxpane/1.2.0/jars/syntaxpane.jar
/home/hhrutz/.ivy2/local/de.sciss/topology_2.12/1.1.1/jars/topology_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/treetable-java/1.5.0/jars/treetable-java.jar
/home/hhrutz/.ivy2/local/de.sciss/treetable-scala_2.12/1.5.0/jars/treetable-scala_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/wolkenpumpe-basic_2.12/2.29.0/jars/wolkenpumpe-basic_2.12.jar
/home/hhrutz/.ivy2/local/de.sciss/wolkenpumpe-core_2.12/2.29.0/jars/wolkenpumpe-core_2.12.jar
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar

Declared library dependencies:
com.github.scopt:scopt:3.7.1
de.sciss:audiowidgets-app:1.14.0
de.sciss:audiowidgets-swing:1.14.0
de.sciss:desktop:0.10.0
de.sciss:equal:0.1.3
de.sciss:fileutil:1.1.3
de.sciss:fscape:2.20.0
de.sciss:jump3r:1.0.5
de.sciss:kollflitz:0.2.3
de.sciss:lucre-bdb:3.11.0
de.sciss:lucre-core:3.11.0
de.sciss:lucre-expr:3.11.0
de.sciss:lucreswing:1.14.0
de.sciss:model:0.3.4
de.sciss:numbers:0.2.0
de.sciss:patterns-lucre:0.7.0
de.sciss:pdflitz:1.4.0
de.sciss:raphael-icons:1.0.5
de.sciss:scalacollider:1.28.0
de.sciss:scalacolliderswing-core:1.41.0
de.sciss:scalacolliderswing-interpreter:1.41.0
de.sciss:scalacolliderugens-spec:1.19.2
de.sciss:scalainterpreterpane:1.10.0
de.sciss:sonogramoverview:1.11.0
de.sciss:soundprocesses-compiler:3.24.0
de.sciss:soundprocesses-views:3.24.0
de.sciss:span:1.4.2
de.sciss:submin:0.2.4
de.sciss:swingplus:0.4.0
de.sciss:topology:1.1.1
de.sciss:weblaf:2.1.4
de.sciss:wolkenpumpe:2.29.0
jline:jline:2.14.6
org.pegdown:pegdown:1.6.0
org.scala-lang:scala-library:2.12.8
[warn] Mellite >>> The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "de.sciss" %% "audiowidgets-app" % "1.14.0"
[warn]  - "de.sciss" %% "audiowidgets-swing" % "1.14.0"
[warn]  - "de.sciss" %% "desktop" % "0.10.0"
[warn]  - "de.sciss" %% "equal" % "0.1.3"
[warn]  - "de.sciss" %% "fscape" % "2.20.0"
[warn]  - "de.sciss" % "jump3r" % "1.0.5"
[warn]  - "de.sciss" %% "kollflitz" % "0.2.3"
[warn]  - "de.sciss" %% "lucre-bdb" % "3.11.0"
[warn]  - "de.sciss" %% "lucre-core" % "3.11.0"
[warn]  - "de.sciss" %% "lucre-expr" % "3.11.0"
[warn]  - "de.sciss" %% "lucreswing" % "1.14.0"
[warn]  - "de.sciss" %% "numbers" % "0.2.0"
[warn]  - "de.sciss" %% "patterns-lucre" % "0.7.0"
[warn]  - "de.sciss" %% "pdflitz" % "1.4.0"
[warn]  - "de.sciss" %% "raphael-icons" % "1.0.5"
[warn]  - "de.sciss" %% "scalacollider" % "1.28.0"
[warn]  - "de.sciss" %% "scalacolliderswing-core" % "1.41.0"
[warn]  - "de.sciss" %% "scalacolliderswing-interpreter" % "1.41.0"
[warn]  - "de.sciss" % "scalacolliderugens-spec" % "1.19.2"
[warn]  - "de.sciss" %% "scalainterpreterpane" % "1.10.0"
[warn]  - "de.sciss" %% "sonogramoverview" % "1.11.0"
[warn]  - "de.sciss" %% "soundprocesses-compiler" % "3.24.0"
[warn]  - "de.sciss" %% "soundprocesses-views" % "3.24.0"
[warn]  - "de.sciss" %% "span" % "1.4.2"
[warn]  - "de.sciss" % "submin" % "0.2.4"
[warn]  - "de.sciss" %% "swingplus" % "0.4.0"
[warn]  - "de.sciss" %% "topology" % "1.1.1"
[warn]  - "de.sciss" % "weblaf" % "2.1.4"
[warn]  - "de.sciss" %% "wolkenpumpe" % "2.29.0"
[warn]  - "jline" % "jline" % "2.14.6"
```

So the false positives are still there. Looking at the output, may it be a problem related to locally published jars? All my own libraries are published locally first before going to maven central, so you can see that sbt picks up several libraries from `~/.ivy2/local`.

**Comment by Sciss** [comment]
So after clearing my local jars and forcing new download and cache, the output is

```
[warn] Mellite >>> The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "de.sciss" %% "desktop" % "0.10.0"
[warn]  - "de.sciss" %% "fscape" % "2.20.0"
[warn]  - "de.sciss" %% "kollflitz" % "0.2.3"
[warn]  - "de.sciss" %% "scalacolliderswing-interpreter" % "1.41.0"
[warn]  - "de.sciss" % "scalacolliderugens-spec" % "1.19.2"
[warn]  - "de.sciss" % "weblaf" % "2.1.4"
[warn]  - "de.sciss" %% "wolkenpumpe" % "2.29.0"
[warn]  - "jline" % "jline" % "2.14.6"
```

A few of those are correct:

 - kollflitz (not used at all)
 - weblaf (transitive)
 - jline (transitive)

-------

However others are still incorrect:

 - desktop ; it is a transitive dependency, but it is also explicitly used (for example [here](https://github.com/Sciss/Mellite/blob/6eabaeae225ab867e51e32bd5939b1981869d4ce/src/main/scala/de/sciss/mellite/Prefs.scala#L19))
 - fscape ; not a transitive dependency, used explicitly (for example [here](https://github.com/Sciss/Mellite/blob/fb00a6b0a5b814a60a1aff35e6dc211437c5ca06/src/main/scala/de/sciss/mellite/gui/impl/fscape/FScapeObjView.scala#L116))
 - wolkenpumpe ; not a transitive dependency, used explicitly (for example [here](https://github.com/Sciss/Mellite/blob/8d81f9906a18ea34b1026ecb3481b703ba213e50/src/main/scala/de/sciss/mellite/Init.scala#L20))

It seems the issue here is that the dependencies are aggregate artifacts:

 - desktop wraps desktop-core and others
 - fscape wraps fscape-core and others
 - wolkenpupme wraps wolkenpumpe-core and others

As witnessed by `undeclaredCompileDependencies`:

```
[warn]  - "de.sciss" %% "desktop-core" % "0.10.0"
[warn]  - "de.sciss" %% "fscape-core" % "2.20.0"
[warn]  - "de.sciss" %% "fscape-lucre" % "2.20.0"
[warn]  - "de.sciss" %% "wolkenpumpe-basic" % "2.29.0"
[warn]  - "de.sciss" %% "wolkenpumpe-core" % "2.29.0"
```

That would probably be a separate issue to open.
